[package]
name = "umbra-rpc"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
umbra-core = { path = "../umbra-core" }

solana-sdk = "3.0.0"
solana-transaction-status = "3.1.1"

bs58 = "0.5"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
