[package]
name = "umbra-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.17"
solana-client = "3.1.1"
solana-sdk = "2.3.1"
solana-transaction-status = "3.1.1"
umbra-core = { path = "../umbra-core" }